# Typos spell checker config
# https://github.com/crate-ci/typos/blob/master/docs/reference.md
[default]
extend-ignore-words-re = [
  # Ignore words with up to 3 characters (typically abbreviations)
  '^[a-zA-Z]{1,3}$',
]

[files]
extend-exclude = [
  # Ignore these files
  "voc4cat.ttl",
]

[default.extend-words]
linke = "linke"

# Example to ignore certain words only in specific files
# [type.voc4cat_ttl]
# extend-glob = ["voc4cat.ttl"]
# check-file = false
# extend-ignore-words-re = [
#   # Ignore words case insensitive
#   "(?i)\\b(syntesized)\\b",
#   # Ignore the exact word
#   # "\\bsyntesized\\b",
# ]
